### ISSUE TITLE
Native modules such as sqlite3 was missed on Linux and Windows version

### ISSUE THREAD

**Issue by hardliner66** [LanceGin/Mockman#1]
The prebuilt crashes on Windows because sqlite3 is missing.

![image](https://user-images.githubusercontent.com/2937272/46472942-03315800-c7df-11e8-912b-5e688abab381.png)

**Comment by IslandOfCode** [comment]
Same here.
I think it's a package problem, because i try (i don't really know nodejs that well, so...) to manually install sqlite with nodejs, but nothing.

Btw, task manager show a bunch "Electron" process, after several try. Maybe mockman don't close that gracefully, after all.

I will try to build from source, but i use windows, so i have to install linux somewhere to do that.

**Comment by IslandOfCode** [comment]
Ok i try the precompiled linux version: exactly the same error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Please install sqlite3 package manually
    at new ConnectionManager (/home/riccardo/Scaricati/Mockman-linux-x64/Mockman-linux-x64/resources/app.asar/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:31:15)
    at new SqliteDialect (/home/riccardo/Scaricati/Mockman-linux-x64/Mockman-linux-x64/resources/app.asar/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
...
```

Then i try to compile from source (on a Ubuntu 18.04 vbox): no luck, same error.

Thing is, the sqlite3 module is installed during execution of native.sh script.

**Comment by IslandOfCode** [comment]
@LanceGin 
First thing first: **prebuild** don't work.
```
npm ERR! missing script: prebuild
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     rebuild
npm ERR!     build
```
Second: **wine** need to be installed. It is something that should be specified.
Just for refecence: i install `wine-development 3.16-1`


Execute **native.sh** again, and realize there is an error, something like:
`gyp ERR! stack Error: EACCES: permission denied, mkdir ...`
He complain about the fact he cant create the sqlite directory.

So i give 0777 recursively to every file and dir, just to be sure, and run native.sh again.

Then i give `npm run build`: and everything goes fine (apart for mac version, for obvious reason).

The linux version now start (at least, i have not tried it yet), but the **win32** version (after move it on my windows 8.1) dont, with the same error.

So i try to run the win version on my linux box with wine, i get, again, the same error.
![schermata del 2018-10-05 10-07-12](https://user-images.githubusercontent.com/33231231/46524990-b30fcf80-c88a-11e8-95f4-4865b38b46e7.png)

The problem lies within the packaging of the win version, problem is: i don't know very well nodejs, electron, vue etc. Can't help with that, i'm afraid.

**Comment by LanceGin** [comment]
@IslandOfCode sorry, I mean `npm run rebuild`, not `prebuild`


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by IslandOfCode** [comment]
Nothing, again the problem is only with the win version.

**Comment by LanceGin** [comment]
@hardliner66 @IslandOfCode 

The problem you faced has been fixed, and Mockman has been built to `dmg for MacOS`, `NSIS for Windows` and `AppImage for Linux`.  You can just redownload it from [release](https://github.com/LanceGin/Mockman/releases/tag/1.0.0). 

What caused this `native module missing` problem is just the `building tool`, I used `electron-packager` to build all versions across the platform, so on the non-macOS, native modules were missing. 

Now I have change the building tool from `electron-packager` to `electron-builder`, and I use some ci framework to build the version of the specific platform(travis-ci for macOS and Linux, Appveyor for windows).

btw, if you want to compile the project from the source code now, you can just run 
```
npm install
npm run dev
```
